

num_rounds: 5 # number of FL rounds in the experiment
num_clients: 5  # number of total clients available (this is also the number of partitions we need to create)
batch_size: 20 # batch size to use by clients during training
fraction_fit: 0.3
num_clients_per_round_fit: 5 # number of clients to involve in each fit round (fit  round = clients receive the trained_models from the server and do local training)

